# This is a basic workflow to help analyze open API specs against API Guidelines

name: CI - Diff specs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SPEC_FOLDER: openapi

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  diff:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "csv"
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            if [[ $added_modified_file == ${SPEC_FOLDER}* ]]; then
              service="${added_modified_file#*/}"
              service="${service%%.*}"
              echo "Diffing ${added_modified_file} for service ${service}"
              ./.bin/apiregistryctl diff ${added_modified_file} -s ${service} -o text
            fi
          done
